== Allgemeines
=== Rechtliche Grundlagen
//Todo Links und Anhänge definieren 
Seit dem 1. Juli 2008 ist das https://www.fedlex.admin.ch/eli/cc/2008/388/de[Bundesgesetz über Geoinformation (GeoIG, SR 510.62)] in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des https://www.sz.ch/public/upload/assets/48275/214_110.pdf?fp=2[kantonalen Geoinformationsgesetzes (KGeoiG, SRSZ 214.110)]. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die https://www.sz.ch/public/upload/assets/5600/214_111.pdf?fp=11[kantonale Verordnung über Geoinformation (KGeoiV, SRSZ 214.111)] in Kraft. Sie präzisiert das KGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.


===  Zweck des Dokuments
Im Jahre 2024 wurde das Thema der Waldfeststellungen überarbeitet und frisch aufgesetzt. Neu sind in diesem Thema sämtliche Klassen enthalten, welche im Rahmen einer Waldfeststellung benötigt werden. Diese Klassen sind:
 
* *Stockgrenze*
* *Waldgrenze*
* *Wirkbereiche der Waldgrenzen*

Die Waldgrenze ist Bestandteil des ÖREB-Katasters. +

Diese Dokumentation richtet sich an:

* *Personen der zuständigen kantonalen Fachstelle,* welche die Daten nachführen,
* *Personen der Geoinformation,* welche die Daten nach diesem Modell prozessieren, veröffentlichen oder in andere Modelle überführen, sowie
* *Dritte,* welche sich über das Thema informieren.


===  Verweise auf andere Themen
Das vorliegende Thema führt die Geometrien der Stockgrenze, Waldgrenze und Wirkbereiche. Die Verfahren, welchen bei Änderungen durchlaufen werden, sind im Thema

* https://ch-sz-geo.github.io/A241/docs/modelldokumentation.html[Verfahren Waldrecht (A241)]

beschrieben.

Vor der Zusammenlegung wurden die Daten in separaten Themen nachgeführt. Diese waren:

* *Stockgrenzen (A010)* und
* *Waldgrenzen A053)*

Diese Themen bleiben bestehen und werden neu automatisch aufgrund der Änderungen im Thema *"Waldfeststellung"* nachgeführt. Analoges gilt für die Nachführung der Stockgrenzen im GeoShop und die der Waldgrenzen im ÖREB-Kataster.


ifdef::backend-pdf[]
<<<
endif::[]
