== Allgemeines
=== Rechtliche Grundlagen
//Todo Links und Anhänge definieren 
Seit dem 1. Juli 2008 ist das https://www.fedlex.admin.ch/eli/cc/2008/388/de[Bundesgesetz über Geoinformation (GeoIG)] in Kraft. Am 1. Juli 2012
erfolgte die vollständige Inkraftsetzung des https://www.sz.ch/public/upload/assets/48275/214_110.pdf?fp=2[kantonalen Geoinformationsgesetzes (KGeoiG)]. Es hat
zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen.

Am 1. Januar 2013 trat die https://www.sz.ch/public/upload/assets/5600/214_111.pdf?fp=11[kantonale Verordnung über Geoinformation (KGeoiV)] in Kraft. Sie
präzisiert das KGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 „Katalog der
Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 „Katalog der
Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die
Ausarbeitung eines Geodatenmodells zuständig sind.


===  Zweck des Dokuments
Im Jahre 2024 wurde das Thema der Waldfeststellungen überarbeitet und frisch aufgesetzt. Dabei wurde der Prozess der Waldfeststellung berücksichtigt und alle Klassen, die dabei eine Rolle spielen, in dieses Thema zusammengefasst. Diese sind:
 
* *Stockgrenze*
* *Waldgrenze*
* *Wirkbereiche der Waldgrenzen*

Die Waldgrenze ist Bestandteil des ÖREB-Katasters. +

Diese Dokumentation richtet sich an:

* *Personen der zuständigen kantonalen Fachstelle,* um das Thema zu beschreiben und die Dokumentation aktuell zu halten,
* *Personen der Geoinformation,* um Daten nach diesem Modell abzugeben oder in andere Modelle zu transformieren, sowie
* *Dritte,* um sich über das Thema zu informieren.


===  Verweise auf andere Themen
Im vorliegenden Thema werden die Geometrien der Stockgrenze, Waldgrenze und Wirkbereiche geführt. Die Verfahren, welche zur Ausscheidung dieser Geometrien zur Anwendung kommen, sind im Thema

* https://ch-sz-geo.github.io/A241/docs/modelldokumentation.html[Verfahren Waldrecht (A241)]

beschrieben.

Die Themen

* *Stockgrenzen (A010)* und
* *Waldgrenzen A053)*

bleiben bestehen. Sie werden über eine Datentransformation aus dem Thema *"Waldfeststellung"* bedient. Die zuständige Stelle führt die Daten nur noch im Thema "Waldfeststellung" nach. Alles andere, wie die Publikation der Stockgrenzen im GeoShop oder die der Waldgrenzen im ÖREB-Kataster erfolgt automatisch.


ifdef::backend-pdf[]
<<<
endif::[]
