== Allgemeines
=== rechtliche Grundlagen
Seit dem 1. Juli 2008 ist das Bundesgesetz über Geoinformation (GeoIG, SR 510.62) <<allgemeines.adoc#doc-01,[1]>> in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des kantonalen Geoinformationsgesetzes (kGeoiG, SRSZ 214.110) <<allgemeines.adoc#doc-03,[3]>>. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die kantonale Verordnung über Geoinformation (kGeoiV, SRSZ 214.111) <<allgemeines.adoc#doc-04,[4]>> in Kraft. Sie präzisiert das kGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.

=== Zweck des Dokuments
Im Jahre 2024 wurde das Thema der Waldfeststellungen überarbeitet und frisch aufgesetzt. Neu sind in diesem Thema sämtliche Klassen enthalten, welche im Rahmen einer Waldfeststellung benötigt werden. Diese Klassen sind:
 
* *Stockgrenze*
* *Waldgrenze*
* *Wirkbereiche der Waldgrenzen*

Die Waldgrenze ist Bestandteil des ÖREB-Katasters.

===  Verweise auf andere Themen
Das vorliegende Thema führt die Geometrien der Stockgrenze, Waldgrenze und Wirkbereiche. Die Verfahren, welchen bei Änderungen durchlaufen werden, sind im Thema

* https://ch-sz-geo.github.io/A241/docs/modelldokumentation.html[Verfahren Waldrecht (A241)]

beschrieben.

Vor der Zusammenlegung wurden die Daten in separaten Themen nachgeführt. Diese waren:

* *Stockgrenzen (A010)* und
* *Waldgrenzen A053)*

Diese Themen bleiben bestehen und werden neu automatisch aufgrund der Änderungen im Thema *"Waldfeststellung"* nachgeführt. Analoges gilt für die Nachführung der Stockgrenzen im GeoShop und die der Waldgrenzen im ÖREB-Kataster.

=== Zielgruppen
Dieses Dokument richtet sich an folgende Nutzergruppen:

* **Fachstellen für Modellierung,** die den inhaltlichen Rahmen des Themas festlegen,
* **Datenbearbeiterinnen und -bearbeiter,** die sich über die Prozesse und Methoden der Datenpflege informieren,
* **Verantwortliche für die Datenpublikation,** die die Daten entsprechend der Freigabestufe veröffentlichen und die Transformation in andere Modelle durchführen sowie
* **Endnutzerinnen und Endnutzer,** die sich über den Inhalt und die Struktur der Daten informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
